@startuml
title Owner Context - Owner Aggregate

package "Owner Aggregate" {
  class Owner {
    - ownerId: UUID
    - name: String
    - contact: String
    - cpf: String
    - payment: PaymentVO
    --
    + registerOwner()
    + updateOwner()
    + deleteOwner()
    + registerVehicle()
    + updateVehicle()
    + deleteVehicle()
    + getVehicle()
    + findVehicleByPlate(String plate)
    + getPaymentMethod()
    + changePaymentMethod(PaymentVO newPayment)
  }

  class Vehicle {
    - vehicleId: UUID
    - ownerId: UUID
    - color: String
    - licensePlate: String
    - model: String
  }

  Owner "1" *-- "0..*" Vehicle : owns
}
@enduml
