@startuml
title Ticket Aggregate (Ticketing Context)

package "Ticket Aggregate" {
  class Ticket {
    - ticketId: UUID
    - vehiclePlate: vehiclePlateVO
    - entryDateTime: OffsetDateTime
    - exitDateTime: OffsetDateTime
    - status: TicketStatus
    --
    + createTicket()
    + closeTicket()
    + authorizeEntry()
    + calculateFee()
    + releaseExit()
  }

  interface DomainEvent

  class TicketCreated implements DomainEvent
  class TicketClosed implements DomainEvent

  Ticket "1" ..> TicketCreated : emits >
  Ticket "1" ..> TicketClosed : emits >
}
@enduml